#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Apr 09, 2021 03:30:41 PM CEST  platform: Windows NT

import sys
from spacy import displacy
import spacy
import os


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global corpus
    corpus = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def runButton():
    example = corpus.get()
    print("I got the corpus")
    nlp = spacy.load("./best_model")
    print("NER loaded")
    doc = nlp(example)

    html = displacy.render(doc, style='ent')
    with open("data_visualisation.html", "w") as file:
        file.write(html)
    print("html page created")
    file.close()

    import webbrowser
    new = 2
    url = os.getcwd() + '/data_visualisation.html'
    print(url)
    webbrowser.open(url, new=new)
    print("html page opened")
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import runModel
    runModel.vp_start_gui()




